export const plantsArray = [
    {
        commonName: 'Taro',
        scientificName: 'Colocasia esculenta',
        // image: '~/src/images/Taro.png',
        image: 'Taro.png',
        size: '',
        easeOfCare: '',
        whereToGrow: '',
        careLight: '',
        careWater: '',
        endemicTo: '',
    },
    {
        commonName: 'String of Bananas',
        scientificName: 'Curio radicans',
        // image: '~/src/images/StringofBananas.png.png',
        image: 'StringofBananas.png',
        size: '',
        easeOfCare: '',
        whereToGrow: '',
        careLight: '',
        careWater: '',
        endemicTo: '',
    },
    {
        commonName: 'Snake Plant',
        scientificName: 'Dracaena trifasciata',
        // image: '~/src/images/SnakePlant.png',
        image: 'SnakePlant.png',
        size: '',
        easeOfCare: '',
        whereToGrow: '',
        careLight: '',
        careWater: '',
        endemicTo: '',
    },
    {
        commonName: 'Prayer Plant',
        scientificName: 'Maranta leuconeura',
        // image: '~/src/images/PrayerPlant.png',
        image: 'PrayerPlant-min.png',
        size: '',
        easeOfCare: '',
        whereToGrow: '',
        careLight: '',
        careWater: '',
        endemicTo: '',
    },
    {
        commonName: 'Monstera',
        scientificName: 'Monstera deliciosa',
        // image: '~/src/images/Monstera.png',
        image: 'Monsterra.png',
        size: '',
        easeOfCare: '',
        whereToGrow: '',
        careLight: '',
        careWater: '',
        endemicTo: '',
    },
    {
        commonName: 'Money Plant',
        scientificName: 'Pachira glabra ',
        // image: '~/src/images/MoneyPlant.png',
        image: 'MoneyPlant.png',
        size: '',
        easeOfCare: '',
        whereToGrow: '',
        careLight: '',
        careWater: '',
        endemicTo: '',
    },
    {
        commonName: 'Mexican Petunia',
        scientificName: 'Ruellia simplex',
        // image: '~/src/images/MexicanPetunia.png',
        image: 'MexicanPetunia.png',
        size: '',
        easeOfCare: '',
        whereToGrow: '',
        careLight: '',
        careWater: '',
        endemicTo: '',
    },
    {
        commonName: 'Lavender Scallops',
        scientificName: 'Kalanchoe fedtschenkoi',
        // image: '~/src/images/MexicanPetunia.png',
        image: 'LavenderScallops.png',
        size: '',
        easeOfCare: '',
        whereToGrow: '',
        careLight: '',
        careWater: '',
        endemicTo: '',
    },
    {
        commonName: 'Garden Croton',
        scientificName: 'Codiaeum variegatum',
        // image: '~/src/images/MexicanPetunia.png',
        image: 'GardenCroton.png',
        size: '',
        easeOfCare: '',
        whereToGrow: '',
        careLight: '',
        careWater: '',
        endemicTo: '',
    },
    {
        commonName: 'Elephant Bush',
        scientificName: 'Portulacaria afra',
        // image: '~/src/images/MexicanPetunia.png',
        image: 'ElephantBush.png',
        size: '',
        easeOfCare: '',
        whereToGrow: '',
        careLight: '',
        careWater: '',
        endemicTo: '',
    },
    {
        commonName: 'Common Coleus',
        scientificName: 'Coleus scutellarioides',
        // image: '~/src/images/MexicanPetunia.png',
        image: 'CommonColeus.png',
        size: '',
        easeOfCare: '',
        whereToGrow: '',
        careLight: '',
        careWater: '',
        endemicTo: '',
    },
    {
        commonName: 'Arrow Plant',
        scientificName: 'Syngonium podophyllum',
        // image: '~/src/images/MexicanPetunia.png',
        image: 'ArrowPlant.png',
        size: '',
        easeOfCare: '',
        whereToGrow: '',
        careLight: '',
        careWater: '',
        endemicTo: '',
    },
    {
        commonName: 'Blood Leaf',
        scientificName: 'Iresine rhizomatosa',
        // image: '~/src/images/MexicanPetunia.png',
        image: 'BloodLeaf.png',
        size: '',
        easeOfCare: '',
        whereToGrow: '',
        careLight: '',
        careWater: '',
        endemicTo: '',
    },
    {
        commonName: 'Blue Chalkstick',
        scientificName: 'Curio repens, syn Senecio Serpens',
        // image: '~/src/images/MexicanPetunia.png',
        image: 'BlueChalkstick.png',
        size: '',
        easeOfCare: '',
        whereToGrow: '',
        careLight: '',
        careWater: '',
        endemicTo: '',
    },
]

